behaviors:
  flappy:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 8196
      num_epoch: 3
      learning_rate: 2.5e-4
      learning_rate_schedule: linear
      beta: 5.0e-3
      beta_schedule: linear
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 3
    time_horizon: 64
    max_steps: 5000000
    checkpoint_interval: 500000
    keep_checkpoints: 100
    summary_freq: 1000
