# behaviors:
#   FlappyBird:
#     trainer_type: ppo
#     hyperparameters:
#       batch_size: 1024
#       buffer_size: 20480
#       learning_rate: 0.0001 # 3e-4
#       beta: 0.003 # 0.001
#       epsilon: 0.3 # 0.2
#       lambd: 0.9 # 0.95 -> 0.92 -> 0.9
#       num_epoch: 5
#       learning_rate_schedule: linear
#     #   entropy_regularization: 0.01
#     #   normalize: true
#       hidden_units: 512 # 256
#       num_layers: 3 # 2
#       vis_encode_type: simple
#     reward_signals:
#       extrinsic:
#         gamma: 0.99
#         strength: 1.0
#         normalize: true
#       curiosity:
#         strength: 0.02
#         gamma: 0.99
#     keep_checkpoints: 5
#     max_steps: 5000000
#     time_horizon: 128
#     summary_freq: 5000
behaviors:
  FlappyBird:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 3e-4
      beta: 0.003
      epsilon: 0.3
      lambd: 0.9
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: true
    #   curiosity:
    #     strength: 0.01
    #     gamma: 0.99
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 5000